### ISSUE TITLE
Error while compiling truffle contract

### ISSUE THREAD

**Issue by supportreq** [nikhildsahu/E-Certify#13]
**Describe the bug**
I am trying to perform the steps as per the readme document. While compiling the contracts I am getting the following error:
deploy/contracts/SimpleStorage.sol:1:1: ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.24;
^---------------------^

Error: Truffle is currently using solc 0.5.16, but one or more of your contracts specify "pragma solidity 0.4.24".
Please update your truffle config or pragma statement(s).
(See https://trufflesuite.com/docs/truffle/reference/configuration#compiler-configuration for information on
configuring Truffle to use a specific solc compiler version.)

Compilation failed. See above.

**Comment by supportreq** [comment]
@nikhildsahu ?

**Comment by nikhildsahu** [comment]
I don't think we can run the project now.

This project was built almost 2 years back for a hackathon. 
Many major dependencies are not working, and need some tweaks.

**Comment by Singh-Anshuman1** [comment]
if you know the project won't run what is the use of putting it on GitHub?  It's better to delete it instead of wasting time and fooling people.
