### ISSUE TITLE
This contract object doesn't have address set yet, please set an address first.

### ISSUE THREAD

**Issue by sohail-coder** [nikhildsahu/E-Certify#29]
![Screenshot from 2022-04-24 18-08-51](https://user-images.githubusercontent.com/51455139/164981616-7dad98d6-223c-445d-8f9a-ba31145c1f8a.png)

**Comment by hrithick19** [comment]
+1, facing same error @nikhildsahu

**Comment by sohail-coder** [comment]
> +1, facing same error @nikhildsahu

They are no longer maintaining the repo. and majority of the dependencies are outdated and depreciated because of that the above errors raises.
